title: Mike Kaperys
email: mike@kaperys.io
author: Mike Kaperys <mike@kaperys.io>

description: "Sheffield based PHP developer"
baseurl: "/"
url: "https://kaperys.io"

permalink: pretty

highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

sass:
 style: compressed

gems:
  - jekyll-feed
  - bourbon
  - neat

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
