title: Mike Kaperys
email: mike@kaperys.io
author: Mike Kaperys <mike@kaperys.io>

description: "Sheffield based PHP developer"
baseurl: "/"
url: "https://kaperys.io"

highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

sass:
 style: compressed

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
