title: Mike Kaperys
email: mike@kaperys.io
url: "https://kaperys.io"
permalink: pretty
description: Mike Kaperys is a software engineer from Sheffield, UK.

highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

plugins:
  - jekyll-feed

include:
  - _pages

sass:
  style: compressed
